version: "3.9"

services:
  app:
    container_name: laravue
    build: .
    volumes:
      - ${PROJECT_PATH:-../../laravue-monolito-app}:/var/www/html
    ports:
      - "8000:8000"
      - "5173:5173" # Porta do Vite (Frontend)
    environment:
      - USER_ID=${UID:-1000}
      - GROUP_ID=${GID:-1000}