version: "3.9"

services:
  app:
    container_name: vue_app
    build: .
    working_dir: /app
    volumes:
      - ${PROJECT_PATH:-../../vue-app}:/var/www/html
    ports:
      - "5173:5173"
    environment:
      - USER_ID=${UID:-1000}
      - GROUP_ID=${GID:-1000}