version: "3.9"

services:
  app:
    container_name: laravel_generator
    build: .
    volumes:
      - ${PROJECT_PATH:-../../api-laravel-app}:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - USER_ID=${UID:-1000}
      - GROUP_ID=${GID:-1000}