version: "3.9"

services:
  flutter:
    container_name: flutter_app
    build: .
    ports:
      - "8081:8081"
    volumes:
      # Cria na pasta 'flutter_app' dois níveis acima por padrão, ou onde você definir
      - ${PROJECT_PATH:-../../flutter_app}:/app
    environment:
      - API_URL=http://host.docker.internal:8000
      - USER_ID=${UID:-1000}
      - GROUP_ID=${GID:-1000}